// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ReadingIsGood.ProductService.Context;

namespace ReadingIsGood.ProductService.Migrations
{
    [DbContext(typeof(ProductServiceDbContext))]
    internal class ProductServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProductService")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReadingIsGood.ProductService.Entities.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .HasMaxLength(100)
                    .HasColumnType("VARCHAR(100)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Stock")
                    .IsConcurrencyToken()
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Product");
            });

            modelBuilder.Entity("ReadingIsGood.ProductService.Entities.Product", b =>
            {
                b.OwnsOne("ReadingIsGood.ProductService.Entities.AuditInformation", "AuditInformation", b1 =>
                {
                    b1.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b1.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b1.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b1.HasKey("ProductId");

                    b1.ToTable("Product");

                    b1.WithOwner()
                        .HasForeignKey("ProductId");
                });

                b.Navigation("AuditInformation");
            });
#pragma warning restore 612, 618
        }
    }
}